id = "sonamu"
name = "Sonamu"
description = "Sonamu development support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["CartaNova <https://github.com/cartanova-ai>"]
repository = "https://github.com/cartanova-ai/vscode-sonamu"

[language_servers.sonamu]
name = "Sonamu"
languages = ["TypeScript", "TSX", "JSON"]
